### ISSUE TITLE
BUG: super_clipboard Cause PlatformException(channel-error, Unable to establish connection on channel., null, null) on Android devices

### ISSUE THREAD

**Issue by EMUNES** [superlistapp/super_native_extensions#353] opened 2024-05-06 14:26 UTC
I found this exception always occur on Android devices, if I use `super_clipboard` (or packages depending on `super_clipboard`, like `flutter_quill`) with `shared_preferences` package. I can use `shared_preference` with other dozens of packages, but once with `super_clipboard`, the exception occurs which I can not get rid of. I report this BUG here because this is the only platform-related package I can find to cause this problem.

This exception will cause Android app unable to open. The app will hang.

This exception won't occur on Windows11 build. It won't occur if `super_clipboard` is the only package dependency. 

ENV: flutter version: 3.19.6 and dart 3.3.4, Windows 11
VERSION: `supper_clipboard` 0.7.3 up to 0.8.12

Minimal code for reproduce:

*pubspec.yml*:

```yaml
name: fix
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3 # Persistent settings.
  # flutter_quill: "9.0.0"
  super_clipboard: "0.7.3" # up to "8.0.12"
  # flutter_keyboard_visibility: ^6.0.0 # no problem.
  # url_launcher: ^6.2.6 # no problem.
  # device_info_plus: ^10.1.0 # no problem.

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

Main code to run:

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final prefs = await SharedPreferences.getInstance(); // Exception here.

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

**Comment by dovecheng** [comment] 2024-05-07 06:13
dependency_overrides:
  irondash_engine_context: 0.5.1

**Comment by knopp** [comment] 2024-05-08 07:59
Can you post here verbose log from flutter build?

**Comment by EMUNES** [comment] 2024-05-08 09:42
Yes.

```
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
�ƶ���         1 ���ļ���
Resolving dependencies...
  args 2.4.2 (2.5.0 available)
* build_tool 1.0.0 from path C:/Users/HZB/AppData/Local/Pub/Cache/hosted/pub.dev/irondash_engine_context-0.4.1/cargokit/build_tool (was 1.0.0 from path c:/Users/HZB/AppData/Local/Pub/Cache/hosted/pub.dev/irondash_engine_context-0.4.1/cargokit/build_tool)     
  github 9.17.0 (9.24.0 available)
  http 1.1.0 (1.2.1 available)
  path 1.8.0 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  toml 0.14.0 (0.15.0 available)
  version 3.0.0 (3.0.2 available)
Changed 1 dependency!
7 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
INFO: Precompiled binaries are disabled
INFO: Building irondash_engine_context_native for x86_64-linux-android
INFO: Building irondash_engine_context_native for i686-linux-android
INFO: Building irondash_engine_context_native for x86_64-linux-android
�ƶ���         1 ���ļ���
Resolving dependencies...
  args 2.4.2 (2.5.0 available)
* build_tool 1.0.0 from path C:/Users/HZB/AppData/Local/Pub/Cache/hosted/pub.dev/super_native_extensions-0.7.3/cargokit/build_tool (was 1.0.0 from path c:/Users/HZB/AppData/Local/Pub/Cache/hosted/pub.dev/super_native_extensions-0.7.3/cargokit/build_tool)     
  github 9.17.0 (9.24.0 available)
  http 1.1.0 (1.2.1 available)
  path 1.8.0 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  toml 0.14.0 (0.15.0 available)
  version 3.0.0 (3.0.2 available)
Changed 1 dependency!
7 packages have newer versions incompatible with dependency constraints.
Try `dart pub outdated` for more information.
Compiling bin/build_tool_runner.dart to kernel file bin/build_tool_runner.dill.
INFO: Precompiled binaries are disabled
INFO: Building super_native_extensions for x86_64-linux-android
INFO: Building super_native_extensions for i686-linux-android
INFO: Building super_native_extensions for x86_64-linux-android
Running Gradle task 'assembleDebug'...                             24.7s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/flutter ( 5277): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 5277):
Syncing files to device sdk gphone64 x86 64...                     229ms

Flutter run key commands.
r Hot reload.
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on sdk gphone64 x86 64 is available at: http://127.0.0.1:28806/N0Iyc3sOWjs=/
The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:28806/N0Iyc3sOWjs=/
```

Then the app will hang and not open on Android.

**Comment by knopp** [comment] 2024-05-08 10:43
This indeed looks like a duplicate of https://github.com/superlistapp/super_native_extensions/issues/352. I'll see if I can reproduce this. Could be a change in recent Rust.

**Comment by EMUNES** [comment] 2024-05-09 04:59
This problem occurs after we upgrade `flutter` to 3.19.6 and `rust` from 1.77 to 1.78. So yes, it could be a rust problem instead.

**Comment by knopp** [comment] 2024-05-09 06:54
Thanks for confirmation. There does seem to be a change of behavior where 1.78 links eh_personality for unoptimized no-std build for some reason. This should be fixed by https://github.com/irondash/irondash/pull/51.

**Comment by EMUNES** [comment] 2024-05-10 02:18
No waiting for merging, I have cloned `irondash` repo and tried this fix locally. The exception is finally gone, and the app runs normally on Android devices. 

Thanks for working on this! Feel free to close this issue, after the fix is merged or not.

**Closed** 2024-05-14 01:56 UTC
