### ISSUE TITLE
Copy a PNG image with super clipboard

### ISSUE THREAD

**Issue by mahdiramezani-mr** [superlistapp/super_native_extensions#74] opened 2023-02-26 13:48 UTC
I have a problem with super clipboard package
I copied a PNG image but after copying it was converted to JPG and the background became black.
How can i fix that?

Thanks for your answers

**Comment by knopp** [comment] 2023-02-26 13:55
You need to provide lot more details here. Which platform? Are you able to reproduce it with the clipboard example?

**Comment by mahdiramezani-mr** [comment] 2023-02-26 14:51
> You need to provide lot more details here. Which platform? Are you able to reproduce it with the clipboard example?

In Android

Original image:

![Screenshot_20230226-180616_Gallery](https://user-images.githubusercontent.com/24915396/221417914-83b20106-c757-4e36-8865-8586f855d8b3.jpg)

After copy:

![Screenshot_20230226-180534_Messages](https://user-images.githubusercontent.com/24915396/221417886-1181ef94-c074-44c9-be8d-d4f67aba0d6d.jpg)

**Comment by knopp** [comment] 2023-02-26 14:54
What is the application that you use to paste?

**Comment by mahdiramezani-mr** [comment] 2023-02-26 15:06
> What is the application that you use to paste?

It's Gboard and I sent the clipboard of Gboard.
When I copied and checked in gboard, the other images had no background.
But when I copied an image with the super clipboard in my app, the image had a black background!

**Comment by knopp** [comment] 2023-02-26 16:07
This seems to be a GBoard bug with some PNG files. I could reproduce the issue with GBoard, but when pasting to google docs for example the image shows correctly with transparent background.

**Comment by mahdiramezani-mr** [comment] 2023-02-26 17:57
> This seems to be a GBoard bug with some PNG files. I could reproduce the issue with GBoard, but when pasting to google docs for example the image shows correctly with transparent background.

How can I copy an image without this problem in Flutter?
GBoard has no problem with other PNG images from other apps ):

**Comment by knopp** [comment] 2023-02-26 19:51
Unfortunately I can not answer that. This seems to be a bug in GBoard and I can't really tell which part of generated PNG is confusing it:

1) Copy the image from Flutter
2) Paste it to Google Keep (it will paste properly transparent)
3) Copy the image from Google Keep (now no Flutter code is involved, it's being copied by Google Keep)
4) The image shows with black background in GBoard

So the problem seems to be that something in the generated image is confusing GBoard. But the image works properly on all other platforms and on all other software than GBoard.

Since generating the image is not part of super_native_extension I will close this issue.

**Closed by knopp** 2023-02-26 19:51 UTC
