### ISSUE TITLE
[super_context_menu] Feature request: left button click support

### ISSUE THREAD

**Issue by mgenware** [superlistapp/super_native_extensions#199] opened 2023-09-09 17:40 UTC
![image](https://github.com/superlistapp/super_native_extensions/assets/11565096/3911ddf6-75f3-44bf-9558-de3c95e7021c)

In our case, we would like to show a context menu when the '...' button is clicked. Right now, super_context_menu seems to only support right clicks on desktop. It would be great if left clicks are also supported.

**Comment by f-person** [comment] 2023-09-13 06:08
Would it make sense to allow folks to programmatically open/trigger the context menu so that everyone can implement their desired behaviors? 👀

**Comment by knopp** [comment] 2023-09-13 15:26
Closing as duplicate of https://github.com/superlistapp/super_native_extensions/issues/189.

This is a valid request and I do have plans for implementing this, but no timeline. It's not a small thing to get right considering we're supporting 5 platforms + web.

**Closed by knopp** 2023-09-13 15:26 UTC
