### ISSUE TITLE
Reading file from clipboard throws virtualFileReceiveError

### ISSUE THREAD

**Issue by adil192** [superlistapp/super_native_extensions#86] opened 2023-03-19 16:24 UTC
When running `reader.getFile(Formats.png, ...)` on Windows 11, I get this exception:
`
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(super_native_extensions_error, virtual file receive error: item not found, virtualFileReceiveError, null)
`
This doesn't occur if I set `allowVirtualFiles` to false in the `reader.getFile` call.

### Code snippet
```dart
final reader = await ClipboardReader.readClipboard();
final futures = <Future>[];
for (SimpleFileFormat format in formats) {
  if (!reader.canProvide(format)) continue;
  reader.getFile(format, (file) {
    futures.add(processFile(file, format));
  });
}
await Future.wait(futures);
```
- the `processFile` function never gets run since `reader.getFile` throws without running the `onFile` callback.
- `formats` is a list of image formats (`Formats.jpeg`, `Formats.png`, etc) but when I tested with just `Formats.png` the error still occured.

**Comment by knopp** [comment] 2023-03-19 17:08
Seems like a regression. Which application are you trying to copy from?

**Comment by adil192** [comment] 2023-03-19 17:19
I'm copying an image file from the Windows file explorer

**Comment by knopp** [comment] 2023-03-19 20:50
This seems to be a bug in windows explorer IDataObject implementation. Should now be fixed in `main`.

**Closed** 2023-03-19 20:50 UTC
